image: archlinux
shell: true
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/REPOSITORIES:RO git.sr.ht/PROFILE:RO
packages:
  - ghcup-hs-bin
  - sed
  - gawk
  - hut
  - neovim
  - xclip
  - pacman-contrib
secrets:
  - f8bf6699-0178-4e2e-8d63-2e4f61dd4803
  - 4fa9ff23-b0bb-48a9-ac83-de3fe3e51052
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
sources:
  - https://git.sr.ht/~petrus/mailctl
  - https://aur.archlinux.org/mailctl-bin
tasks:
  - mirror: |
      cd mailctl
      git push --mirror git@github.com:pdobsan/mailctl
  - setup-buildenv: |
      echo 'export PATH=~/.ghcup/bin:~/.cabal/bin:~/.local/bin:$PATH' >> .buildenv
      echo 'alias ls="ls --color=auto -alF --group-directories-first"' >> .buildenv
  - setup-ghc: |
      mkdir -p .cabal/bin
      ghcup install ghc 9.4.4
      ghcup set ghc 9.4.4
      ghcup install cabal 3.8.1.0
      ghcup set cabal 3.8.1.0
      ghcup list -c set
      cabal update
  - build-mailctl: |
      cd mailctl
      cabal build
      cabal install --install-method=copy
  - test: |
      mkdir -p ~/.local/var/mailctl ~/.config/mailctl
      mailctl -h
      mailctl --version
  - release: |
      cd mailctl
      tag=$(git describe --exact-match 2>/dev/null || true)
      if [[ -z "$tag" ]]; then
        echo "Current commit is not a tag; not uploading."
        exit 0
      fi
      cd
      reldir=$(mailctl --version | head -1 | awk '{print $1 "-" $3}')
      mkdir $reldir
      cp ~/.cabal/bin/mailctl $reldir/$reldir-$(uname -s)-$(uname -m)
      cp mailctl/{LICENSE,README.md} $reldir
      cp -r mailctl/configs $reldir
      cp -r mailctl/completions $reldir
      tar cfz $reldir.tgz $reldir
      hut git artifact upload --rev "$tag" -r mailctl $reldir.tgz
  - aur: |
      cd mailctl
      version=$(awk '/^version:/ {print $2}' mailctl.cabal)
      tag=$(git describe --exact-match 2>/dev/null || true)
      if [[ $tag !=  $version ]]; then
        echo "tag = $tag and version = $version differ!"
        exit 1
      fi
      cd aur
      sed -i "s/pkgver=.*/pkgver=$tag/" PKGBUILD
      makepkg --printsrcinfo >.SRCINFO
      updpkgsums
      cp PKGBUILD .INSTALL .SRCINFO ../mailctl-bin
      cd ../mailctl-bin
      git commit -a -m "release $tag"
      git push
