image: archlinux
shell: true
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/REPOSITORIES:RO git.sr.ht/PROFILE:RO
packages:
  - ghcup-hs-bin
  - sed
  - gawk
  - neovim
  - xclip
secrets:
  - f8bf6699-0178-4e2e-8d63-2e4f61dd4803
sources:
  - https://git.sr.ht/~petrus/mailctl
tasks:
  - mirror: |
      cd mailctl
      git push --mirror git@github.com:pdobsan/mailctl
  - setup-buildenv: |
      echo 'export PATH=~/.ghcup/bin:~/.cabal/bin:~/.local/bin:$PATH' >> .buildenv
  - setup-ghc: |
      mkdir -p .cabal/bin
      ghcup install ghc 9.4.4
      ghcup set ghc 9.4.4
      ghcup install cabal 3.8.1.0
      ghcup set cabal 3.8.1.0
      ghcup list -c set
      cabal update
  - build-mailctl: |
      cd mailctl
      cabal build
      cabal install --install-method=copy
  - test: |
      mkdir -p ~/.local/var/mailctl ~/.config/mailctl
      mailctl -h
      mailctl --version
      #mailctl printenv
      reldir=$(mailctl --version | head -1 | awk '{print $1 "-" $3}')
      mkdir $reldir
      cp ~/.cabal/bin/mailctl $reldir/$reldir-$(uname -s)-$(uname -m)
      cp mailctl/{LICENSE,README.md} $reldir
      tar cfz mailctl.tgz $reldir
artifacts:
  - mailctl.tgz
