image: archlinux
shell: true
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/REPOSITORIES:RO git.sr.ht/PROFILE:RO
packages:
  - ghcup-hs-bin
  - sed
  - gawk
  - hut
  - neovim
  - xclip
  - pacman-contrib
  - bash_completion
  - keychain
secrets:
  - f8bf6699-0178-4e2e-8d63-2e4f61dd4803
  - 4fa9ff23-b0bb-48a9-ac83-de3fe3e51052
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
sources:
  - https://git.sr.ht/~petrus/mailctl
tasks:
  - mirror: |
      cd mailctl
      git push --mirror git@github.com:pdobsan/mailctl

  - setup-buildenv: |
      cd mailctl
      version=$(awk '/^version:/ {print $2}' mailctl.cabal)
      tag=$(git describe --exact-match 2>/dev/null || echo none)
      cd
      echo "export VERSION=$version" >> .buildenv
      echo "export TAG=$tag" >> .buildenv
      echo 'export PATH=~/.ghcup/bin:~/.cabal/bin:~/.local/bin:$PATH' >> .buildenv
      echo 'alias ls="ls --color=auto -alF --group-directories-first"' >> .buildenv

  - setup-ghc: |
      mkdir -p .cabal/bin
      ghcup install ghc 9.4.4
      ghcup set ghc 9.4.4
      ghcup install cabal 3.8.1.0
      ghcup set cabal 3.8.1.0
      ghcup list -c set
      cabal update

  - build-mailctl: |
      cd mailctl
      cabal freeze
      cabal build
      cabal install --install-method=copy

  - test: |
      mkdir -p ~/.local/var/mailctl ~/.config/mailctl
      mailctl -h
      mailctl --version

  - release: |
      reldir="mailctl-$VERSION"
      mkdir $reldir
      cp ~/.cabal/bin/mailctl $reldir/$reldir-$(uname -s)-$(uname -m)
      cp mailctl/{LICENSE,README.md} $reldir
      cp -r mailctl/configs $reldir
      cp -r mailctl/completions $reldir
      cp mailctl/cabal.project.freeze $reldir
      tar cfz $reldir.tgz $reldir

      ln -s $reldir.tgz mailctl.tgz
      if [[ $TAG != none ]]; then
        hut git artifact upload --rev "$TAG" -r mailctl $reldir.tgz
      fi

  - aur: |
      eval $(keychain --eval f8bf6699-0178-4e2e-8d63-2e4f61dd4803 4fa9ff23-b0bb-48a9-ac83-de3fe3e51052)
      git clone ssh://aur@aur.archlinux.org/mailctl-bin.git

      cd mailctl/aur
      sed -i "s/^pkgver=.*/pkgver=$TAG/" PKGBUILD
      makepkg --printsrcinfo >.SRCINFO
      updpkgsums
      cp PKGBUILD .INSTALL .SRCINFO ~/mailctl-bin

      cd ~/mailctl-bin
      git commit -a -m "release $TAG"
      git push

      if [[ $TAG !=  $VERSION ]]; then
        echo "WARNING: tag=$TAG != version=$VERSION"
      fi

artifacts:
  - mailctl.tgz

