# The primary purpose of mailctl is providing IMAP/SMTP clients with the
# capabilities of renewal and authorization of OAuth2 credentials. 
# Accordingly only the OAuth2 related config entries are mandatory.

# Any path can be absolute or rooted to your home directory using ~/

# These four entries are used for OAuth2 access method
services_file: ~/.config/mailctl/services.yaml
oauth2_dir: ~/.local/var/mailctl
# This encryption method using gnupg.
# Alternatives like age can also be configured here.
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - YOUR-KEY-ID
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt

# Only if you are using fdm
fdm_config: ~/.config/fdm/fdm.conf
fdm_accounts: ~/.config/fdm/accounts.conf

# Only if you are running mailctl directly by cron
cron_indicator: ~/.local/var/mailctl/fdm-cron-enabled

# Only if you are using a password manager for traditional access methods
# This is an example of using `pass`
password_store: ~/.local/var/password-store
pass_cmd:
  exec: pass
  args:
    - email/

