# The purpose of oama is providing IMAP/SMTP clients with the
# capabilities of renewal and authorization of OAuth2 credentials. 

# Any path can be absolute or rooted to the home directory 
# using tilde expansion (~/...)

services_file: ~/.config/oama/services.yaml

# OAuth2 credentials are kept in the Gnome keyring or
# in GPG encrypted files
#
# Only one of these methods can be used!!!
# Delete what you don't use.

# Storing OAuth credentials in the Gnome keyring
# +
ring_store:
  exec: secret-tool
  args:
    - store
    - --label

ring_lookup:
  exec: secret-tool
  args:
    - lookup
    - oama
# -

# Saving OAuth2 credentials in files encrypted by GPG
# +
oauth2_dir: ~/.local/var/oama
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - YOUR-KEY-ID
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt
# -
