google:
  auth_endpoint: https://accounts.google.com/o/oauth2/auth
  token_endpoint: https://accounts.google.com/o/oauth2/token
  redirect_uri: http://localhost:8080
  auth_scope: https://mail.google.com/
  client_id: YOUR-APP-CLIENT-ID
  client_secret: YOUR-APP-CLIENT-SECRET

microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  redirect_uri: https://login.microsoftonline.com/common/oauth2/nativeclient
  auth_scope: |
    https://outlook.office365.com/IMAP.AccessAsUser.All
    https://outlook.office365.com/SMTP.Send
    offline_access
  tenant: common
  client_id: YOUR-APP-CLIENT-ID
  client_secret: YOUR-APP-CLIENT-SECRET

