# Refs.: https://github.com/haskell-actions/setup
name: Build oama - basic
on:
  workflow_dispatch
jobs:
  cabalbuild:
    name: cabal build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: latest
          cabal-version: latest
      - run: |
          cabal update
          cabal build
          cabal run oama
