name: Build Matrix

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # additionally run three times per week at midnight to maintain cache
    - cron: '0 0 * * Mon,Wed,Sat'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.2.4', '9.4.1']
        cabal: [latest]
        os: [ubuntu-latest]
    name: Haskell GHC ${{ matrix.ghc }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Install external dependencies
        run: |
          sudo apt-get update

      - name: Freeze
        run: cabal freeze

      - name: Restore ~/.cabal
        uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: cabal build --only-dependencies

      - name: Build & Install
        run: |
          cabal build
          cabal install --install-method=copy --overwrite-policy=always --enable-executable-stripping
