name: Release

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/build.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: package-binary
        run: |
          echo $PATH
          ~/.cabal/bin/mailctl --version


